version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app  # Optional for dev

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Siddhant@9
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sql-data:/var/opt/mssql  # Persist data
      - ./initdb:/initdb         # Just mount init folder (script runs in sql_init)

  sql_init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./initdb:/initdb
    entrypoint: >
      /bin/bash -c "
      sleep 20;
      /opt/mssql-tools/bin/sqlcmd -S db -U sa -P 'Siddhant@9' -i /initdb/init.sql;
      "

networks:
  app-network:
    driver: bridge

volumes:
  sql-data: