version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network
    ports:
      - "1433:1433"  # Expose the SQL Server port to your local machine (optional)
  
  web:
    build: .
    environment:
      - FLASK_APP=app.py
      - DB_SERVER=${DB_SERVER}
      - DB_PORT=1433
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "5000:5000"

networks:
  app-network:
    driver: bridge
